name: weather_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  intl: ^0.18.1
  http: ^1.1.0
  fluttertoast: ^8.2.2
  geocoding: ^2.1.1
  country_state_city_picker: ^1.2.8
  sqflite: ^2.3.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_animate: ^4.2.0+1
  connectivity_plus: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/domine/Domine-Regular.ttf

    - family: Handjet
      fonts:
        - asset: assets/fonts/handjet/Handjet-Regular.ttf
    
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf